version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: okr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: okr_db
      POSTGRES_USER: okr_user
      POSTGRES_PASSWORD: your-password-word
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    volumes:
      - /opt/okr/pg_data:/var/lib/postgresql/data
    command: >
      postgres
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=off
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U okr_user -d okr_db"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  default:
    name: okr-network
